version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - '${PG_PORT}:${PG_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
